config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "contact" => "pages#contact"
  get "about" => "pages#about"
  get "help" => "pages#help"
  get "create_stor_info" => "pages#create_stor_info"
  get "cart/add" =>"cart#add"
  get "cart/delete" =>"cart#delete"
  get "cart/delete_all" => "cart#delete_all"
  get "cart/show" =>"cart#show"
  get "clear" => "cart#clear"

  resources :orders do
    collection do
      get "vue_table"
    end
  end

  resources :payments, only: [] do
    # member do payments/:id/foo
    #   get "foo"
    # end
    collection do #payments/foo
      get "checkout"
      get "successful"
      post "execute"
    end
  end

  resources :stores do
    resources :products do
      resources :reviews
    end
  end

  namespace :manager do
    resources :stores do
      resources :orders do
        collection do
          get "statistic"
        end
      end
      resources :products do
        collection do
          get "export"
          get "import"
          post "post_import"
        end
      end
    end

    resources :products, only: [:index]
  end

  resources :products, only: [:index]
  resources :users

  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_products
  has_many :products, through: :order_products
  belongs_to :store
  has_one :payment

  validates :name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :address, presence: true
  validates :country, presence: true
  validates :zip, presence: true
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :store
  belongs_to :category
  has_many :order_products
  has_many :orders, through: :order_products
  has_many :reviews

  mount_uploaders :images, ImageUploader
  serialize :images # , JSON  If you use SQLite, add this line.

  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :discount, presence: true

  def price_with_discount
    price - discount
  end

  def calc_rating
    if reviews.count > 0
      (reviews.sum(:rating).to_f / reviews.count).round(1)
    else
      return 0
    end
  end

  def update_rating
    self.rating = calc_rating
    save
  end

  after_update do
    store.update_rating
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user

  after_create do
    product.update_rating
  end
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :products, :dependent => :destroy
  has_many :orders
  belongs_to :user

  validates :name, presence: true
  validates :description, presence: true
  validates :phone, presence: true, length: { minimum: 9 }

  def store_new_orders
    orders.where(:status => :new).count
  end

  def calc_rating
    if products.count > 0
      (products.sum(:rating) / products.count).round(1)
    else
      return 0
    end
  end

  def update_rating
    self.rating = calc_rating
    save
  end
end

app/models/store_user.rb
class StoreUser < ApplicationRecord
  belongs_to :user
  belongs_to :store
end

app/models/user.rb
class User < ApplicationRecord
  has_many :stores, :dependent => :destroy
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create do
    UserMailer.with(user: self).welcome_email.deliver_later
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :load_cart

  def add
    @cart.add_product(product_id)

    redirect_to cart_show_path
  end

  def show
    @products = @cart.products
    @sum = @cart.sum
  end

  def delete
    @cart.delete_product(product_id)

    redirect_to cart_show_path
  end

  def delete_all
    @cart.delete_all_product(product_id)

    redirect_to cart_show_path
  end

  def clear
    @cart.clear_product

    redirect_to cart_show_path
  end

  def product_id
    params[:product_id].to_s
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/manager_helper.rb
module ManagerHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cart/show.html.erb
<h1> Your cart </h1>
<hr/>
<% if @products.empty? %>
  <p>Your cart is empty</p>
<% else %>
  <%= link_to "Clear", clear_path %>
  <% @products.each do |product| %>
    <div class = "d-flex row justify-content-between col-12 ">
      <div class = "col-3">
        <span> <%= product.name %> </span>
      </div>

      <div class = "row justify-content-end align-items-center col-8">
          <%= link_to "+", cart_add_path({:product_id => product.id}), title:"add", class:"btn btn-primary rounded-pill px-3 col-1" %>

          <span class="col-1"> <%= @cart.count(product.id.to_s)%> </span>

          <%= link_to "-", cart_delete_path({:product_id => product.id}), title:"delete", class:"btn btn-danger rounded-pill px-3 col-1" %>

          <span class = "d-flex flex-row-reverse col-2"> <%= number_to_currency(product.price_with_discount) * @cart.count(product.id.to_s) %></span>

          <%= link_to "", cart_delete_all_path({:product_id => product.id}), title:"delete_all", class:"btn-close btn_close col-1" %>
      </div>
    </div>
    <hr/>
  <%end%>

  <div class="row justify-content-between">
  <div class="col-4">
    <%= link_to "Place order", new_order_path,  class:"btn btn-primary rounded-pill" %>
  </div>
  <div class="d-flex flex-row-reverse align-self-center col-4">
    <strong><%= number_to_currency(@sum) %></strong>
  </div>
  </div>

<% end %>