config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "contact" => "pages#contact"
  get "about" => "pages#about"
  get "help" => "pages#help"
  get "create_stor_info" => "pages#create_stor_info"
  get "cart/add" =>"cart#add"
  get "cart/delete" =>"cart#delete"
  get "cart/delete_all" => "cart#delete_all"
  get "cart/show" =>"cart#show"
  get "clear" => "cart#clear"

  resources :orders do
    collection do
      get "vue_table"
    end
  end

  resources :payments, only: [] do
    # member do payments/:id/foo
    #   get "foo"
    # end
    collection do #payments/foo
      get "checkout"
      get "successful"
      post "execute"
    end
  end

  resources :stores do
    resources :products do
      resources :reviews
    end
  end

  namespace :manager do
    resources :stores do
      resources :orders do
        collection do
          get "statistic"
        end
      end
      resources :products do
        collection do
          get "export"
          get "import"
          post "post_import"
        end
      end
    end

    resources :products, only: [:index]
  end

  resources :products, only: [:index]
  resources :users

  root "home#index"
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :products, :dependent => :destroy
  has_many :orders
  belongs_to :user

  validates :name, presence: true
  validates :description, presence: true
  validates :phone, presence: true, length: { minimum: 9 }

  def store_new_orders
    orders.where(:status => :new).count
  end

  def calc_rating
    if products.count > 0
      (products.sum(:rating) / products.count).round(1)
    else
      return 0
    end
  end

  def update_rating
    self.rating = calc_rating
    save
  end
end

app/controllers/manager/orders_controller.rb
class Manager::OrdersController < ManagerController
  def index
    status = params[:status]
    if status.nil?
      status = "new"
    end

    @store = Store.find(params[:store_id])
    @orders = @store.orders
    @orders = @orders.order(:created_at => :DESC)

    @orders = @orders.where(status: status)
  end

  def show
    @order = Order.find(params[:id])
    @order_products = @order.order_products
    @products = @order.products
  end

  def statistic
    @store = Store.find(params[:store_id])
    @orders = @store.orders

    @data_keys = Array.new(7) do |i|
      date = Time.now - i.day
      date.strftime("%d.%m.%g")
    end
    @data_keys = @data_keys.reverse

    @data_values = Array.new(7) do |i|
      date = Time.now.to_date - i.day
      orders = @orders.where("DATE(created_at) = DATE(?)", date)
      orders = orders.count
    end
    @data_values = @data_values.reverse
    # @data_keys = [
    #   Time.now.strftime("%d.%m.%g"),
    #   (Time.now - 1.day).strftime("%d.%m.%g"),
    #   (Time.now - 2.day).strftime("%d.%m.%g"),
    #   (Time.now - 3.day).strftime("%d.%m.%g"),
    #   (Time.now - 4.day).strftime("%d.%m.%g"),
    #   (Time.now - 5.day).strftime("%d.%m.%g"),
    #   (Time.now - 6.day).strftime("%d.%m.%g")
    # ]
    # @data_values = [1, 10, 7, 4, 20, 24, 15]
  end

  def destroy
  end
end

app/controllers/manager/products_controller.rb
class Manager::ProductsController < ManagerController
  before_action :store
  # include ExportProduct
  # include ImportProduct

  def new
    @product = store.products.new
    @categories = Category.all
  end

  def create
    @product = store.products.create(product_params)

    if @product.save
      redirect_to manager_store_path(@store)
    else
      return render(:new, status: :unprocessable_entity)
    end
  end

  def edit
    @product = store.products.find(params[:id])
    @categories = Category.all
  end

  def update
    @product = store.products.find(params[:id])

    if @product.update(product_params)
      redirect_to manager_store_path(@store)
    else
      render :edit
    end
  end

  def destroy
    @product = store.products.find(params[:id])
    @product.destroy
    redirect_to manager_store_path(@store)
  end

  def export
    export_product
  end

  def import
  end

  def post_import
    file = params[:file]
    file_data = file.read
    store_id = @store.id
    file_type = params[:file].content_type
    ImportProductJob.perform_later(file_type, file_data, store_id)
    redirect_to manager_store_path(@store.id), notice: "import in progress"
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :discount, { images: [] }, :category_id)
  end

  def store
    @store ||= current_user.stores.find(params[:store_id])
  end
end

app/controllers/manager/stores_controller.rb
class Manager::StoresController < ManagerController
  def index
    @stores = Store.where(:user_id => current_user.id)
  end

  def show
    @store = Store.find(params[:id])
  end

  def edit
    @store = current_user_store
  end

  def update
    @store = current_user_store

    if @store.update(store_params)
      redirect_to @store
    else
      render :edit
    end
  end

  def destroy
    @store = current_user_store
    @store.destroy

    redirect_to current_user
  end

  private

  def store_params
    params.require(:store).permit(:name, :description, :phone)
  end

  def current_user_store
    current_user.stores.find(params[:id])
  end

  def manager
    store = Store.find(params[:id])
    if current_user.id != store.user_id
      redirect_to root_url
    end
  end
end

app/controllers/manager_controller.rb
class ManagerController < ApplicationController
  before_action :authenticate_user!
  before_action :manager

  def manager
    store = Store.find(params[:store_id])
    if current_user.id != store.user_id
      redirect_to root_url
    end
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @stores = Store.all
  end

  def show
    @store = Store.find(params[:id])
    @categories = Category.all
  end

  def new
    @store = Store.new
  end

  def create
    @store = Store.new(store_params)
    @store.user_id = current_user.id

    if @store.save
      redirect_to manager_store_orders_path(@store.id)
    else
      return render(:new, status: :unprocessable_entity)
    end
  end

  private

  def store_params
    params.require(:store).permit(:name, :description, :phone)
  end
end

app/helpers/manager_helper.rb
module ManagerHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/manager/stores/edit.html.erb
<h2> Edit creation </h2>
<main class="m-auto d-flex col-12">
    <div class="col-5">
        <% if @store.errors.any? %>
            <div id="error_explanation" data-turbo-cache="false">
                <ul>
                    <% @store.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>
        <%= form_with model: [ :manager, @store] do |form| %>
            <div class="mb-3">
                <%= form.label :name, class: "form-label" %></br>
                <%= form.text_field :name, required: :true, class: "form-control" %>
            </div>
            <div class="mb-3">
                <%= form.label :description, class: "form-label" %></br>
                <%= form.text_area :description, required: :true, class: "form-control" %>
            </div>
            <div class="mb-3">
                <%= form.label :phone, class: "form-label" %></br>
                <%= form.text_field :phone, required: :true, class: "form-control" %>
            </div>
            <div>
                <%= form.submit "Edit store", class: "btn btn-primary" %>
            </div>
        <% end %>
    </div>
</main>

app/views/manager/stores/show.html.erb
<div class="row g-5">

  <div class="bg-body-tertiary col-md-5 col-lg-4 order-md-last" style="border-radius:20px;background:#6d757d;">
    
    <div class="mt-3 list-group mb-3">
      <%= link_to "Show orders", manager_store_orders_path(@store.id), class:"btn btn-outline-primary" %>
      <hr>
      <%= link_to "Create a new product", new_manager_store_product_path(@store.id), class:"btn btn-outline-primary" %>
      <hr>
      <%= link_to "Statistics", statistic_manager_store_orders_path(@store.id), class:"btn btn-outline-primary" %>
      <hr>
      <%= link_to "Edit store", edit_manager_store_path(@store.id), class:"btn btn-outline-primary" %>
      <hr>
      <%= link_to "Export product to csv", export_manager_store_products_path(@store.id, :format => :csv), class:"btn btn-outline-primary" %> <!--@store.to_export("csv")-->
      <hr>
      <%= link_to "Export product to json", export_manager_store_products_path(@store.id, :format => :json), download:["Products_" + @store.name], class:"btn btn-outline-primary" %>
      <hr>
      <%= link_to "Import product", import_manager_store_products_path(@store.id), class:"btn btn-outline-primary" %>

    </div>

  </div>
  
  <div class="col-md-7 col-lg-8">
    <h2><%= @store.name%> products</h2>

    <div class="col-12 d-flex flex-column">
      <div class="col-11 d-flex justify-content-between">
        <p class="col-6">
          Name
        </p>
        <p class="col-1">
          Price
        </p>
        <p class="col-1">
          Discount
        </p>
        <p class="col-1"></p>
        <p class="col-1"></p>
      </div>

      <% @store.products.each do |product| %>
        <div class="col-11 d-flex justify-content-between bg-body-tertiary manager_store_item_product">
          <div class="d-flex col-6">
            <p class="col-2">
              <img src= <%= product.images[0] %> alt= "<%= product.name%>" class="product_manager_img">
            </p>
            <p class="col-3 px-2">
              <%= product.name %>
            </p>
          </div>
          <p class="col-1">
            <%= number_to_currency(product.price - product.discount) %>
          </p>
          <p class="col-1">
            <%= product.discount %>
          </p>
          <p class="col-1 px-2">
            <%= link_to "Edit", edit_manager_store_product_path(product.store_id, product.id) %>
          </p>
          <p class="col-1 px-2">
            <%= link_to "Delete", manager_store_product_path(product.store_id, product.id), data:{turbo_method: :delete, turbbo_confirm: "Are you surw?"} %>
          </p>
        </div>
      <% end %>
    </div>

  </div>

</div>