config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "contact" => "pages#contact"
  get "about" => "pages#about"
  get "help" => "pages#help"
  get "create_stor_info" => "pages#create_stor_info"
  get "cart/add" =>"cart#add"
  get "cart/delete" =>"cart#delete"
  get "cart/delete_all" => "cart#delete_all"
  get "cart/show" =>"cart#show"
  get "clear" => "cart#clear"

  resources :orders do
    collection do
      get "vue_table"
    end
  end

  resources :payments, only: [] do
    # member do payments/:id/foo
    #   get "foo"
    # end
    collection do #payments/foo
      get "checkout"
      get "successful"
      post "execute"
    end
  end

  resources :stores do
    resources :products do
      resources :reviews
    end
  end

  namespace :manager do
    resources :stores do
      resources :orders do
        collection do
          get "statistic"
        end
      end
      resources :products do
        collection do
          get "export"
          get "import"
          post "post_import"
        end
      end
    end

    resources :products, only: [:index]
  end

  resources :products, only: [:index]
  resources :users

  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_products
  has_many :products, through: :order_products
  belongs_to :store
  has_one :payment

  validates :name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :address, presence: true
  validates :country, presence: true
  validates :zip, presence: true
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :store
  belongs_to :category
  has_many :order_products
  has_many :orders, through: :order_products
  has_many :reviews

  mount_uploaders :images, ImageUploader
  serialize :images # , JSON  If you use SQLite, add this line.

  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :discount, presence: true

  def price_with_discount
    price - discount
  end

  def calc_rating
    if reviews.count > 0
      (reviews.sum(:rating).to_f / reviews.count).round(1)
    else
      return 0
    end
  end

  def update_rating
    self.rating = calc_rating
    save
  end

  after_update do
    store.update_rating
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user

  after_create do
    product.update_rating
  end
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :products, :dependent => :destroy
  has_many :orders
  belongs_to :user

  validates :name, presence: true
  validates :description, presence: true
  validates :phone, presence: true, length: { minimum: 9 }

  def store_new_orders
    orders.where(:status => :new).count
  end

  def calc_rating
    if products.count > 0
      (products.sum(:rating) / products.count).round(1)
    else
      return 0
    end
  end

  def update_rating
    self.rating = calc_rating
    save
  end
end

app/models/store_user.rb
class StoreUser < ApplicationRecord
  belongs_to :user
  belongs_to :store
end

app/models/user.rb
class User < ApplicationRecord
  has_many :stores, :dependent => :destroy
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create do
    UserMailer.with(user: self).welcome_email.deliver_later
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :load_cart

  def add
    @cart.add_product(product_id)

    redirect_to cart_show_path
  end

  def show
    @products = @cart.products
    @sum = @cart.sum
  end

  def delete
    @cart.delete_product(product_id)

    redirect_to cart_show_path
  end

  def delete_all
    @cart.delete_all_product(product_id)

    redirect_to cart_show_path
  end

  def clear
    @cart.clear_product

    redirect_to cart_show_path
  end

  def product_id
    params[:product_id].to_s
  end
end

app/controllers/manager/products_controller.rb
class Manager::ProductsController < ManagerController
  before_action :store
  # include ExportProduct
  # include ImportProduct

  def new
    @product = store.products.new
    @categories = Category.all
  end

  def create
    @product = store.products.create(product_params)

    if @product.save
      redirect_to manager_store_path(@store)
    else
      return render(:new, status: :unprocessable_entity)
    end
  end

  def edit
    @product = store.products.find(params[:id])
    @categories = Category.all
  end

  def update
    @product = store.products.find(params[:id])

    if @product.update(product_params)
      redirect_to manager_store_path(@store)
    else
      render :edit
    end
  end

  def destroy
    @product = store.products.find(params[:id])
    @product.destroy
    redirect_to manager_store_path(@store)
  end

  def export
    export_product
  end

  def import
  end

  def post_import
    file = params[:file]
    file_data = file.read
    store_id = @store.id
    file_type = params[:file].content_type
    ImportProductJob.perform_later(file_type, file_data, store_id)
    redirect_to manager_store_path(@store.id), notice: "import in progress"
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :discount, { images: [] }, :category_id)
  end

  def store
    @store ||= current_user.stores.find(params[:store_id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.order(:name)
    @categories = Category.all

    if params[:search].present?
      @products = @products.where("lower(name) like ?", "%#{params[:search].downcase}%")
    end

    if params[:category_id].present?
      @products = @products.where("lower(category_id) like ?", "%#{params[:category_id].downcase}%")
      @category = Category.find(params[:category_id])
    end
  end

  def show
    @product = Product.find(params[:id])
    @store = @product.store
    @review = Review.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/manager_helper.rb
module ManagerHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_product.html.erb
<div class="col-3">
  <%= link_to store_product_path(product.store_id, product.id), class:"link-dark nav-link", id:"product-cart" do%>
    <div class="card bg-body-tertiary">
      <img src= <%= product.images[0] %> alt= "<%= product.name %>" class="product_card_img">
      <div class="card-body">
        <h5 class="card-title"> <%= product.name %> </h5>
        <small> <%= product.category.name %> </small>

        <div class="d-flex align-items-center">
          <div class="progress progress_card" role="progressbar" aria-label="Basic example" aria-valuenow="<%= product.rating * 20 if product.rating %>" aria-valuemin="0" aria-valuemax="100">
            <div class="progress-bar" style="width: <%= product.rating * 20 if product.rating %>%">
            </div>
          </div>
          <small><%= product.reviews.count %> reviews</small>
        </div>

        <% if product.discount == 0 %>
          <p class="card-text"> <%= number_to_currency(product.price) %>$ </p>
        <% else %>
          <p class="card-text ">
            <span class="discount"><%= number_to_currency(product.price - product.discount) %>$</span>
            <span class="line-through"><%= number_to_currency(product.price) %>$</span>  
          </p>
        <% end %>

        <%= link_to "Buy", cart_add_path({:product_id => product.id}), title:"buy", class:"btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/products/index.html.erb
<div class="d-flex justify-content-between col-12">

  <%= render "home/categories" %>

  <div class="col-10">
    <% if @category %>
      <h2> <span class="product_category_name"><%= @category.name.upcase %></span> PRODUCTS </h2>
    <% else %>
      <h2> ALL PRODUCTS </h2>
    <% end %>

    <div class="row g-4 mt-1">
      <% @products.each do |product| %>
        <%= render product %>
      <% end %>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="">

  <div class="d-flex justify-content-between col-12">
    <div class="col-8 product_show_index">
      <div class="d-flex align-items-center">
        <h2 class="product_name"> <%= @product.name %> </h2>

        <div class="d-flex align-items-center">
          <div class="progress" role="progressbar" aria-label="Basic example" aria-valuenow="<%= @product.rating * 20 if @product.rating %>" aria-valuemin="0" aria-valuemax="100">
            <div class="progress-bar" style="width: <%= @product.rating * 20 if @product.rating%>%">
              <small class="product_rating"> <%= @product.rating if @product.rating %> </small>
            </div>
          </div>
          <small> <%= @product.reviews.count %> reviews</small>
        </div>

      </div>
      <div id="carouselExample" class="carousel slide">
        <div class="carousel-inner">
          <% @product.images.each_with_index do |image, i| %>
            <div class="carousel-item <%= "active" if i == 0 %>">
              <%= image_tag(image.large.url, alt: @product.name, class:"d-block w-100 carousel_image") %>
            </div>
          <% end %>
        </div>

        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    </div>

    <div class="col-3 product_show_side_bloc">
      <div class="d-flex align-items-center side_bloc_price_wrap">
        <% if @product.discount == 0 %>
          <span class="card-text h4 side_bloc_price"> <%= number_to_currency(@product.price) %>$ </span>
        <% else %>
          <span class="discount h4 side_bloc_price"><%= number_to_currency(@product.price - @product.discount) %>$</span>
          <span class="line-through"><%= @product.price %>$</span>
        <% end %>

        <%= link_to cart_add_path({product_id: @product.id}), class:"btn btn-primary d-flex align-items-center product_side_bloc_button" do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart3" viewBox="0 0 16 16">
            <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
          </svg>
          <span>Buy</span>
        <% end %>
      </div>

      <div class="d-flex align-items-center">
        <div class="product_show_store_side_bloc">
          <span class="product_show_store_name_side_bloc"> Store: <%= link_to @product.store.name, store_path(@product.store.id) %></span>
        </div>

          <div class="progress" role="progressbar" aria-label="Basic example" aria-valuenow="<%= @product.store.rating * 20 %>" aria-valuemin="0" aria-valuemax="100">
            <div class="progress-bar" style="width: <%= @product.store.rating * 20 %>%">
              <small class="product_rating"> <%= @product.store.rating.round(1) if @product.rating %> </small>
            </div>
          </div>

      </div>
      
    </div>
    
  </div>

  <div class="d-flex justify-content-between col-12 product_show_under_blok">
    <div class="col-8 prooduct_description_show_under_blok">
      <h4 class="h3">Product discription</h4>
      <p class="pt-2"> 
        <%= @product.description %>
      </p>
    </div>
    <div class="col-3 reviews">
      <div class="reviews_form">
        <h4>Reviews</h4>
        <%= render "reviews/form" %>
      </div>

      <div class="reviews_views">
        <%= render @product.reviews.order(:id => :DESC) %>
      </div>
    </div>
  </div>

</div>