config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "contact" => "pages#contact"
  get "about" => "pages#about"
  get "help" => "pages#help"
  get "create_stor_info" => "pages#create_stor_info"
  get "cart/add" =>"cart#add"
  get "cart/delete" =>"cart#delete"
  get "cart/delete_all" => "cart#delete_all"
  get "cart/show" =>"cart#show"
  get "clear" => "cart#clear"

  resources :orders do
    collection do
      get "vue_table"
    end
  end

  resources :payments, only: [] do
    # member do payments/:id/foo
    #   get "foo"
    # end
    collection do #payments/foo
      get "checkout"
      get "successful"
      post "execute"
    end
  end

  resources :stores do
    resources :products do
      resources :reviews
    end
  end

  namespace :manager do
    resources :stores do
      resources :orders do
        collection do
          get "statistic"
        end
      end
      resources :products do
        collection do
          get "export"
          get "import"
          post "post_import"
        end
      end
    end

    resources :products, only: [:index]
  end

  resources :products, only: [:index]
  resources :users

  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_products
  has_many :products, through: :order_products
  belongs_to :store
  has_one :payment

  validates :name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :address, presence: true
  validates :country, presence: true
  validates :zip, presence: true
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :store
  belongs_to :category
  has_many :order_products
  has_many :orders, through: :order_products
  has_many :reviews

  mount_uploaders :images, ImageUploader
  serialize :images # , JSON  If you use SQLite, add this line.

  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :discount, presence: true

  def price_with_discount
    price - discount
  end

  def calc_rating
    if reviews.count > 0
      (reviews.sum(:rating).to_f / reviews.count).round(1)
    else
      return 0
    end
  end

  def update_rating
    self.rating = calc_rating
    save
  end

  after_update do
    store.update_rating
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user

  after_create do
    product.update_rating
  end
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :products, :dependent => :destroy
  has_many :orders
  belongs_to :user

  validates :name, presence: true
  validates :description, presence: true
  validates :phone, presence: true, length: { minimum: 9 }

  def store_new_orders
    orders.where(:status => :new).count
  end

  def calc_rating
    if products.count > 0
      (products.sum(:rating) / products.count).round(1)
    else
      return 0
    end
  end

  def update_rating
    self.rating = calc_rating
    save
  end
end

app/models/store_user.rb
class StoreUser < ApplicationRecord
  belongs_to :user
  belongs_to :store
end

app/models/user.rb
class User < ApplicationRecord
  has_many :stores, :dependent => :destroy
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create do
    UserMailer.with(user: self).welcome_email.deliver_later
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/manager_helper.rb
module ManagerHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
    <%=link_to "Ali Shop", root_path, class:"mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1" %>
    <span class="mb-3 mb-md-0 text-body-secondary">© 2023</span>
    </div>

    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
      <li class="ms-3"><%=link_to "Contact", contact_path, class:"nav-link text-muted" %></li>
      <li class="ms-3"><%=link_to "About", about_path, class:"nav-link text-muted" %></li>
      <li class="ms-3"><%=link_to "Help", help_path, class:"nav-link text-muted" %></li>
    </ul>
  </footer>

app/views/layouts/_header.html.erb
<header class="p-3 mb-3 border-bottom">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <%= link_to "Ali Shop", root_path, class:"nav-link px-2 link-secondary" %>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">


          <% if current_user %>
            <% current_user.stores.each do |store|%>
              <li>
                <%= link_to manager_store_orders_path(store.id), class:"nav-link px-2 link-dark", id:"store_link" do %> 
                  <%= store.name %>
                  <% if store.store_new_orders != 0 %>
                    <span class="badge rounded-pill bg-danger">
                      <%= store.store_new_orders %>
                    </span>
                  <% end %>
                <% end %>
              </li>
            <% end %>
          <% end %>
          <!--<li><%= link_to "Home", root_path, class:"nav-link px-2 link-dark" %></li>
          <li><%= link_to "All Store", stores_path, class:"nav-link px-2 link-dark" %></li>
          <li><%= link_to "All Products", products_path, class:"nav-link px-2 link-dark" %></li>-->
          <li>
            <%= form_tag(products_path, method: :get) do %>
              <div class="d-flex">
                <%= text_field_tag "search", params[:search], placeholder: "Search...", class:"form-control me-2" %>
                <%= submit_tag "Search", class:"btn btn-outline-secondary" %>
              </div> 
            <% end %>
          </li>
        </ul>

        <div>
          <ul class="nav">
          <li><%= link_to cart_show_path, class:"nav-link px-2 link-dark" do %>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart3" viewBox="0 0 16 16">
                  <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                </svg>
              <% end %>
          </li>
            <% if user_signed_in? %>

            <!--<div class="dropdown">
                <a class="btn dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown link
                </a>
                <ul class="dropdown-menu">
                  <li class="nav-item"><%= link_to "Profile", current_user, class:"nav-link link-dark px-2" %></li>
                  <li class="nav-item"><%= link_to "My order", orders_path, class:"nav-link link-dark px-2" %></li>
                  <li class="nav-item"><%= link_to "Setting", edit_user_registration_path, class:"nav-link link-dark px-2" %></li>
                  <li class="nav-item"><%= link_to "Sign out", destroy_user_session_path, class:"nav-link link-dark px-2", data: { turbo_method: :delete } %></li>
                </ul>
              </div>-->

              <li class="nav-item"><%= link_to current_user.name, current_user, class:"nav-link link-dark px-2", id:"profile_link" %></li>
              <li class="nav-item"><%= link_to "Sign out", destroy_user_session_path, class:"nav-link link-dark px-2", data: { turbo_method: :delete } %></li>
            <% else %>
              <li class="nav-item"><%= link_to "Log in", new_user_session_path, class:"nav-link link-dark px-2" %></li>
              <li class="nav-item"><%= link_to "Sign up", new_user_registration_path, class:"nav-link link-dark px-2" %></li>        
            <%end%>
          </ul>
        </div>        
      </div>
    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AliShop</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.1/dist/Chart.min.js"></script>
    <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= render "layouts/header" %>
      <% if notice %>
        <p class="notice"><%= notice %></p>
      <% end %>

      <% if alert %>
        <p class="alert"><%= alert %></p>
      <% end %>
      <%= yield %> 
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>